FROM postgres:9.6.1

ARG pgsql_secret_file=etc/secrets/pgsql
ARG pgsql_repl_secret_file=etc/secrets/pgsql-repl

ENV STKEEPER_CLUSTER_NAME=stolon-cluster \
    STKEEPER_STORE_BACKEND=etcd \
    STKEEPER_STORE_ENDPOINTS=http://localhost:2379 \
    STKEEPER_DATA_DIR=/data/postgres \
    STKEEPER_PG_SU_PASSWORDFILE=/etc/stolon/secrets/pgsql \
    STKEEPER_PG_REPL_PASSWORDFILE=/etc/stolon/secrets/pgsql-repl

RUN mkdir -p ${STKEEPER_DATA_DIR} && \
    chmod 700 ${STKEEPER_DATA_DIR} && \
    chown postgres -R ${STKEEPER_DATA_DIR}
VOLUME ["${STKEEPER_DATA_DIR}"]

COPY ${pgsql_secret_file} ${STKEEPER_PG_SU_PASSWORDFILE}
COPY ${pgsql_repl_secret_file} ${STKEEPER_PG_REPL_PASSWORDFILE}
COPY etc/keeper-entrypoint.sh /usr/local/bin/
RUN chmod 0600 ${STKEEPER_PG_SU_PASSWORDFILE} && \
    chmod 0600 ${STKEEPER_PG_REPL_PASSWORDFILE} && \
    chown postgres ${STKEEPER_PG_SU_PASSWORDFILE} && \
    chown postgres ${STKEEPER_PG_REPL_PASSWORDFILE}

COPY bin/stolon-keeper bin/stolonctl /usr/local/bin/

USER postgres
ENTRYPOINT ["keeper-entrypoint.sh"]
